// worker/bindings.d.ts (generated by wrangler) names the storage bindings by the
// Workers runtime's GLOBAL types, which only exist where @cloudflare/workers-types
// is loaded as `types` — the worker program, not this one. Here the names were
// unresolved, and skipLibCheck made Env['LIBRARY_DB'] and Env['LIBRARY_BUCKET']
// silently `any`, so every D1/R2 call in the library tests went unchecked.
// Aliasing just these two keeps the harness on Node's and the DOM's globals.
import type { D1Database as WorkersD1Database, R2Bucket as WorkersR2Bucket } from '@cloudflare/workers-types';

declare global {
  type D1Database = WorkersD1Database;
  type R2Bucket = WorkersR2Bucket;
}
