// Real browser + local Worker/D1/R2. Requires local auth setup and wrangler dev on 8791.
import fs from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import assert from 'node:assert/strict';
import { devtoolsPort, connect, client } from './browserHarness.mjs';
const root = new URL('../../', import.meta.url);
const origin = process.env.LIBRARY_LOCAL_ORIGIN ?? 'http://127.0.0.1:8791';
if (!['localhost','127.0.0.1'].includes(new URL(origin).hostname)) throw new Error('Smoke must target loopback only');
const session = JSON.parse(await fs.readFile(new URL('.secrets/local-library-session.json',root)));
const doc = JSON.parse(await fs.readFile(new URL('scenarios/lab/00-document/01-minimal-single-note/document.mnx.json',root)));
doc._x = { mnxLab: { work: { title: 'Local library smoke', artist: 'Synthetic fixture' } } };
const bytes = new TextEncoder().encode(JSON.stringify(doc));
const sha256 = Buffer.from(await crypto.subtle.digest('SHA-256', bytes)).toString('hex');
const headers = { Authorization: 'Bearer local-development-only', 'Cf-Access-Jwt-Assertion': session.machine };
const before = await fetch(origin + '/api/library/ingest/LocalSmoke', { headers }); assert.equal(before.status,200);
const { snapshot } = await before.json();
const manifest = { id: 'soundslice:LocalSmoke', expected_revision: snapshot?.piece.revision ?? null,
  source: { kind: 'soundslice', id: 'LocalSmoke' }, renditions: [{ id: 'local-smoke-mnx', format: 'mnx', role: 'original', producer: 'synthetic-test', producer_version: null, producer_options: null, filename: 'local-smoke.mnx.json', sha256, file: 'score' }], recordings: [], tags: [{ dimension: 'unknown', value: 'Test collection', source_ref: 'test' }], canonical: { mode: 'initialize', rendition_id: 'local-smoke-mnx' }, converter_versions: {} };
const form = new FormData(); form.set('manifest',JSON.stringify(manifest)); form.set('score',new Blob([bytes]),'score.mnx.json');
assert.equal((await fetch(origin+'/api/library/ingest',{method:'POST',headers,body:form})).status,200);
const profile = await fs.mkdtemp('/tmp/mnx-library-browser-');
const chrome = spawn(process.env.CHROME_BIN ?? 'google-chrome',['--headless=new','--no-sandbox','--disable-dev-shm-usage','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{stdio:'ignore'});
let ws;
try {
  ws = new WebSocket(await connect(await devtoolsPort(profile))); await once(ws,'open');
  const c = client(ws); await c.send('Runtime.enable'); await c.send('Page.enable'); await c.send('Network.enable');
  const wait = async expression => { for (let i=0;i<100;i++) { if (await c.evaluate(expression)) return; await new Promise(r=>setTimeout(r,100)); } throw new Error('Browser assertion timed out: '+expression+'; '+c.logs.join('; ')); };
  const app = "document.querySelector('mnx-workbench').shadowRoot";
  const dialog = `${app}.querySelector('mnx-library-dialog').shadowRoot`;
  await c.send('Page.navigate',{url:origin});
  await wait(`!!document.querySelector('mnx-workbench')?.shadowRoot?.querySelector('mnx-library-dialog')`);
  await c.evaluate(`${app}.querySelector('mnx-library-dialog').open()`);
  await wait(`${dialog}.textContent.includes('Sign in with email')`);
  assert.equal(await c.evaluate(`${dialog}.querySelector('dialog').open`),true);
  await c.send('Network.setCookie',{name:'CF_Authorization',value:session.browser,url:origin,httpOnly:true,sameSite:'Lax'});
  await c.send('Page.navigate',{url:origin+'/?library=1'});
  await wait(`!!document.querySelector('mnx-workbench')?.shadowRoot?.querySelector('mnx-library-dialog')?.shadowRoot?.textContent.includes('Local library smoke')`);
  await c.evaluate(`${dialog}.querySelector('input').value='title:Local library smoke'; ${dialog}.querySelector('input').dispatchEvent(new Event('input'));`);
  await wait(`${dialog}.querySelector('datalist').textContent !== undefined && ${dialog}.querySelector('datalist option')?.value==='title:Local library smoke'`);
  await c.evaluate(`${dialog}.querySelector('form').dispatchEvent(new Event('submit',{cancelable:true}));`);
  await wait(`${dialog}.querySelector('li button')?.textContent.includes('Local library smoke')`);
  await wait(`!${dialog}.querySelector('li button').disabled`);
  const shot = await c.send('Page.captureScreenshot'); await fs.writeFile('/tmp/mnx-library-dialog.png',Buffer.from(shot.result.data,'base64'));
  await c.evaluate(`${dialog}.querySelector('li button').click()`);
  await wait(`location.hash==='#/document'`);
  await wait(`!!${app}.querySelector('mnx-scenario-page')?.shadowRoot?.querySelector('mnx-document-viewer')?.shadowRoot?.querySelector('svg')`);
  assert.equal(await c.evaluate(`Object.values(localStorage).some(v=>v.includes('Local library smoke') || v.includes('local@example.test'))`),false);
  assert.equal(await c.evaluate(`${dialog}.querySelector('dialog').open`),false);
  console.log('Library smoke passed: sign-in prompt, signed local identity, tag completion/filter, MNX Load, no private localStorage.');
  if (c.logs.length) throw new Error('Browser console errors: '+c.logs.join('\n'));
} finally { ws?.close(); chrome.kill(); await once(chrome,'exit'); await fs.rm(profile,{recursive:true,force:true}); }
