#!/usr/bin/env python3
"""Vendor exact git blobs from a pinned, local upstream clone. No network needed."""
import argparse
from collections import Counter
import hashlib
import io
import json
from pathlib import Path
import subprocess
import xml.etree.ElementTree as ET
import zipfile

PIN = '77c19f7e819154c70ca1a1992e80dcda8ff82fea'
URL = 'https://github.com/w3c-cg/musicxmlTestSuite'
ROOT = Path(__file__).resolve().parents[2]
DEST = ROOT / 'converters/fixtures/musicxml-suite'


def git(repo, *args):
    return subprocess.check_output(['git', '-C', str(repo), *args])


def digest(data):
    return hashlib.sha256(data).hexdigest()


def describe(name, data):
    # ElementTree never fetches the external MusicXML DTD. MXL is read by the
    # independent stdlib ZIP reader here, not by our runtime converter.
    if name.endswith('.mxl'):
        with zipfile.ZipFile(io.BytesIO(data)) as archive:
            container = ET.fromstring(archive.read('META-INF/container.xml'))
            rootfile = next(e for e in container.iter() if e.tag.split('}')[-1] == 'rootfile')
            data = archive.read(rootfile.attrib['full-path'])
    root = ET.fromstring(data)
    descriptions = [
        ' '.join(''.join(e.itertext()).split()) for e in root.iter()
        if e.tag.split('}')[-1] == 'miscellaneous-field' and e.get('name') == 'description'
    ]
    return {
        'root': root.tag.split('}')[-1],
        'version': root.get('version'),
        'description': '\n'.join(descriptions) or None,
        # Presence describes the SOURCE, not importer or renderer support.
        'elements': dict(sorted(Counter(e.tag.split('}')[-1] for e in root.iter()).items())),
    }


def generate(repo):
    files = git(repo, 'ls-tree', '-r', '--name-only', PIN, 'xmlFiles').decode().splitlines()
    blobs = {name: git(repo, 'show', f'{PIN}:{name}') for name in files}
    notices = {name: git(repo, 'show', f'{PIN}:{name}') for name in ['LICENSE', 'README.md']}
    rows = []
    for name, data in sorted(blobs.items()):
        path = Path(name)
        if path.suffix not in {'.musicxml', '.mxl', '.xml'}:
            raise ValueError(f'Unclassified upstream file: {name}')
        rows.append({
            'id': path.stem,
            'path': name,
            'sha256': digest(data),
            'bytes': len(data),
            'format': 'mxl' if path.suffix == '.mxl' else 'musicxml',
            'category': path.name[:2],
            'testClass': 'negative' if '.invalid.' in path.name else
                         'compatibility' if path.name.startswith('99') else 'feature',
            **describe(name, data),
        })
    manifest = {
        'repository': URL, 'revision': PIN, 'license': 'MIT',
        'note': 'Generated by npm run sync:musicxml-suite -- /path/to/upstream-clone. '
                'Source element presence and descriptions are not support claims. '
                'All files under xmlFiles at this revision are included.',
        'notices': {name: digest(data) for name, data in notices.items()},
        'fixtures': rows,
    }
    return {**blobs, **notices, 'manifest.json': (json.dumps(manifest, indent=2, ensure_ascii=False) + '\n').encode()}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('upstream', type=Path)
    parser.add_argument('--check', action='store_true', help='compare only; write nothing')
    args = parser.parse_args()
    output = generate(args.upstream)
    existing = {str(p.relative_to(DEST)) for p in DEST.rglob('*') if p.is_file()}
    stale = existing - output.keys()
    # Never delete unexpected files silently, even though this is a generated tree.
    if stale:
        raise SystemExit(f'Unexpected files in generated tree; review before removing: {sorted(stale)}')
    if args.check:
        changed = [name for name, data in output.items() if not (DEST / name).exists() or (DEST / name).read_bytes() != data]
        if changed:
            raise SystemExit(f'Corpus differs from pinned upstream: {changed}')
    else:
        for name, data in output.items():
            target = DEST / name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
    print(f'{"Checked" if args.check else "Vendored"} {len(output) - 3} fixtures at {PIN}')


if __name__ == '__main__':
    main()
