/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=StorageBindings worker/bindings.d.ts` (hash: a5f602fae09ec1db35d8c6b1757153d9)
interface __BaseEnv_StorageBindings {
	LIBRARY_BUCKET: R2Bucket;
	LIBRARY_DB: D1Database;
	LIBRARY_WRITE_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_StorageBindings {}
}
interface StorageBindings extends __BaseEnv_StorageBindings {}
