/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=StorageBindings worker/bindings.d.ts` (hash: d9d53531ef822281cc1e553cda40a054)
interface __BaseEnv_StorageBindings {
	LIBRARY_BUCKET: R2Bucket;
	LIBRARY_DB: D1Database;
	LIBRARY_WRITE_TOKEN: string;
	LIBRARY_ACCESS_ISSUER: string;
	LIBRARY_ACCESS_AUD: string;
	LIBRARY_INGEST_AUD: string;
	LIBRARY_INGEST_CLIENT_ID: string;
	LIBRARY_LOCAL_JWKS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_StorageBindings {}
}
interface StorageBindings extends __BaseEnv_StorageBindings {}
